export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"

export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
export CODEX_HOME="$XDG_DATA_HOME/codex"

export DOTNET_CLI_TELEMETRY_OPTOUT=1

case "$OSTYPE" in
  darwin*)  # macOS only
    export HOMEBREW_NO_ANALYTICS=1
    export HOMEBREW_NO_AUTO_UPDATE=1
    if [[ "$(uname -m)" = "arm64" ]]; then
      export ARCHFLAGS="-arch arm64"
    fi
    export SHELL_SESSIONS_DISABLE=1
    ;;
  *)
    ;;
esac
